server:
  port: 8080

spring:
  application:
    name: wayfarer-task-request

  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
